// Generated by Frozen Sand Particle Studio
// Mon Sep 26 18:14:58 2011


textures/terminus/thunder
{
	qer_editorimage textures/terminus/thunder
	q3map_cloneshader textures/terminus/zzthunder_fx_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 -120 sin 0 1 0 0.1
	deformvertexes move -897.681 77.2594 0 sawtooth 0 1 0 0.1
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/thunder
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 2 -67 0 0.1
		alphagen const 1
		tcMod rotate -320
		tcMod stretch sawtooth 1 0 0 0.1
	}
}

textures/terminus/zzthunder_fx_1
{
	qer_editorimage textures/terminus/thunder
	q3map_cloneshader textures/terminus/zzthunder_fx_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 -147 sin 0 1 0.986471 0.1
	deformvertexes move -850.736 -311.583 0 sawtooth 0 1 0.986471 0.1
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/thunder
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 2 -67 0.986471 0.1
		alphagen const 1
		tcMod rotate -25
		tcMod stretch sawtooth 1 0 0.986471 0.1
	}
}

textures/terminus/zzthunder_fx_2
{
	qer_editorimage textures/terminus/thunder
	q3map_cloneshader textures/terminus/zzthunder_fx_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 -11 sin 0 1 0.991269 0.1
	deformvertexes move -539.852 -727.596 0 sawtooth 0 1 0.991269 0.1
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/thunder
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 2 -67 0.991269 0.1
		alphagen const 1
		tcMod rotate 19
		tcMod stretch sawtooth 1 0 0.991269 0.1
	}
}

textures/terminus/zzthunder_fx_3
{
	qer_editorimage textures/terminus/thunder
	q3map_cloneshader textures/terminus/zzthunder_fx_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 -91 sin 0 1 0.994086 0.1
	deformvertexes move -894.143 139.761 0 sawtooth 0 1 0.994086 0.1
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/thunder
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 2 -67 0.994086 0.1
		alphagen const 1
		tcMod rotate -315
		tcMod stretch sawtooth 1 0 0.994086 0.1
	}
}

textures/terminus/zzthunder_fx_4
{
	qer_editorimage textures/terminus/thunder
	q3map_cloneshader textures/terminus/zzthunder_fx_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 164 sin 0 1 0.99609 0.1
	deformvertexes move -896.445 79.9135 0 sawtooth 0 1 0.99609 0.1
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/thunder
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 2 -67 0.99609 0.1
		alphagen const 1
		tcMod rotate -246
		tcMod stretch sawtooth 1 0 0.99609 0.1
	}
}

textures/terminus/zzthunder_fx_5
{
	qer_editorimage textures/terminus/thunder
	q3map_cloneshader textures/terminus/zzthunder_fx_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 -106 sin 0 1 0.997647 0.1
	deformvertexes move -229.744 -875.353 0 sawtooth 0 1 0.997647 0.1
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/thunder
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 2 -67 0.997647 0.1
		alphagen const 1
		tcMod rotate 291
		tcMod stretch sawtooth 1 0 0.997647 0.1
	}
}

textures/terminus/zzthunder_fx_6
{
	qer_editorimage textures/terminus/thunder
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 -148 sin 0 1 0.998922 0.1
	deformvertexes move 585.513 668.951 0 sawtooth 0 1 0.998922 0.1
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/thunder
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 2 -67 0.998922 0.1
		alphagen const 1
		tcMod rotate 340
		tcMod stretch sawtooth 1 0 0.998922 0.1
	}
}

// Generated by Frozen Sand Particle Studio
// Thu Sep 24 22:21:54 2009
// Use on a 24x24 unit brush face


textures/terminus/mon_thunder
{
	qer_editorimage textures/terminus/thunder
	q3map_cloneshader textures/terminus/zzmon_thunder_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 40 sin 0 1 0 1
	deformvertexes move -192.8747 787.152 0 sawtooth 0 1 0 0.2
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/thunder
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 2 -57 0 0.2
		alphagen const 1
		tcMod rotate 231
		tcMod stretch sawtooth 1 0 0 0.2
	}
}

textures/terminus/zzmon_thunder_1
{
	qer_editorimage textures/terminus/thunder
	q3map_cloneshader textures/terminus/zzmon_thunder_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 60 sin 0 1 0.988797 0.75
	deformvertexes move -7.39046 791.969 0 sawtooth 0 1 0.988797 0.15
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/thunder
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 2 -47 0.988797 0.15
		alphagen const 1
		tcMod rotate 164
		tcMod stretch sawtooth 1 0 0.988797 0.15
	}
}

textures/terminus/zzmon_thunder_2
{
	qer_editorimage textures/terminus/thunder
	q3map_cloneshader textures/terminus/zzmon_thunder_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 50 sin 0 1 0.993607 0.9
	deformvertexes move 143.8378 790.922 0 sawtooth 0 1 0.993607 0.18
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/thunder
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 2 -52 0.993607 0.18
		alphagen const 1
		tcMod rotate 213
		tcMod stretch sawtooth 1 0 0.993607 0.18
	}
}

textures/terminus/zzmon_thunder_3
{
	qer_editorimage textures/terminus/thunder
	q3map_cloneshader textures/terminus/zzmon_thunder_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 40 sin 0.75 -1 0.996431 0.38
	deformvertexes move -122.212 783.588 0 sawtooth 0 1 0.996431 0.19
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/thunder
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 2 -59 0.996431 0.19
		alphagen const 1
		tcMod rotate 300
		tcMod stretch sawtooth 1 0 0.996431 0.19
	}
}

textures/terminus/zzmon_thunder_4
{
	qer_editorimage textures/terminus/thunder
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 40 sin 0.75 -0.6 0.998439 0.32
	deformvertexes move 18.4406 791.809 0 sawtooth 0 1 0.998439 0.16
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/thunder
		blendfunc GL_ONE GL_ONE
		rgbgen wave sawtooth 2 -45 0.998439 0.16
		alphagen const 1
		tcMod rotate 250
		tcMod stretch sawtooth 1 0 0.998439 0.16
	}
}

// Generated by Frozen Sand Particle Studio
// Mon Sep 26 18:52:22 2011

textures/terminus/mon_fire
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0 0.784
	deformvertexes move -0.755352 1.22297 0 inversesawtooth -0.695684 1 0 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1 0.784
		alphagen wave sawtooth 0 6 0 0.784
		tcMod rotate -33
		tcMod stretch sawtooth 1 -0.7 0 0.784
	}
}

textures/terminus/zzmon_fire_1
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 30 sawtooth 0 1 0.101516 0.784
	deformvertexes move -1.99659 -5.55274 0 inversesawtooth -0.169469 1 0.101516 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.10152 0.784
		alphagen wave sawtooth 0 6 0.101516 0.784
		tcMod rotate -14
		tcMod stretch sawtooth 1 -0.7 0.101516 0.784
	}
}

textures/terminus/zzmon_fire_2
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 43 sawtooth 0 1 0.172346 0.784
	deformvertexes move 1.16215 -0.732783 0 inversesawtooth -0.72786 1 0.172346 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.17235 0.784
		alphagen wave sawtooth 0 6 0.172346 0.784
		tcMod rotate 76
		tcMod stretch sawtooth 1 -0.7 0.172346 0.784
	}
}

textures/terminus/zzmon_fire_3
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 26 sawtooth 0 1 0.234889 0.784
	deformvertexes move 0.143494 6.19449 0 inversesawtooth -0.16139 1 0.234889 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.23489 0.784
		alphagen wave sawtooth 0 6 0.234889 0.784
		tcMod rotate 50
		tcMod stretch sawtooth 1 -0.7 0.234889 0.784
	}
}

textures/terminus/zzmon_fire_4
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 26 sawtooth 0 1 0.292595 0.784
	deformvertexes move 5.98283 1.61183 0 inversesawtooth -0.16139 1 0.292595 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.29259 0.784
		alphagen wave sawtooth 0 6 0.292595 0.784
		tcMod rotate -5
		tcMod stretch sawtooth 1 -0.7 0.292595 0.784
	}
}

textures/terminus/zzmon_fire_5
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 50 sawtooth 0 1 0.34695 0.784
	deformvertexes move 0.859558 0.511038 0 inversesawtooth 1 0 0.34695 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.34695 0.784
		alphagen wave sawtooth 0 6 0.34695 0.784
		tcMod rotate 66
		tcMod stretch sawtooth 1 -0.7 0.34695 0.784
	}
}

textures/terminus/zzmon_fire_6
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_7
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 37 sawtooth 0 1 0.398777 0.784
	deformvertexes move -2.67904 -4.47529 0 inversesawtooth -0.191722 1 0.398777 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.39878 0.784
		alphagen wave sawtooth 0 6 0.398777 0.784
		tcMod rotate -86
		tcMod stretch sawtooth 1 -0.7 0.398777 0.784
	}
}

textures/terminus/zzmon_fire_7
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_8
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 46 sawtooth 0 1 0.448591 0.784
	deformvertexes move 0 -0 0 inversesawtooth 1 0 0.448591 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.44859 0.784
		alphagen wave sawtooth 0 6 0.448591 0.784
		tcMod rotate 40
		tcMod stretch sawtooth 1 -0.7 0.448591 0.784
	}
}

textures/terminus/zzmon_fire_8
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_9
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 23 sawtooth 0 1 0.496744 0.784
	deformvertexes move -4.94232 -5.48227 0 inversesawtooth -0.13548 1 0.496744 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.49674 0.784
		alphagen wave sawtooth 0 6 0.496744 0.784
		tcMod rotate 7
		tcMod stretch sawtooth 1 -0.7 0.496744 0.784
	}
}

textures/terminus/zzmon_fire_9
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_10
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 49 sawtooth 0 1 0.543492 0.784
	deformvertexes move -1.79422 0.902671 0 inversesawtooth -0.497887 1 0.543492 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.54349 0.784
		alphagen wave sawtooth 0 6 0.543492 0.784
		tcMod rotate 61
		tcMod stretch sawtooth 1 -0.7 0.543492 0.784
	}
}

textures/terminus/zzmon_fire_10
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_11
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 34 sawtooth 0 1 0.589025 0.784
	deformvertexes move 2.95209 4.68766 0 inversesawtooth -0.180513 1 0.589025 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.58902 0.784
		alphagen wave sawtooth 0 6 0.589025 0.784
		tcMod rotate 74
		tcMod stretch sawtooth 1 -0.7 0.589025 0.784
	}
}

textures/terminus/zzmon_fire_11
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_12
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 36 sawtooth 0 1 0.633492 0.784
	deformvertexes move -1.00805 -3.17335 0 inversesawtooth 0 1 0.633492 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.63349 0.784
		alphagen wave sawtooth 0 6 0.633492 0.784
		tcMod rotate 61
		tcMod stretch sawtooth 1 -0.7 0.633492 0.784
	}
}

textures/terminus/zzmon_fire_12
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_13
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 25 sawtooth 0 1 0.677012 0.784
	deformvertexes move 7.14711 5.88953 0 inversesawtooth 0 1 0.677012 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.67701 0.784
		alphagen wave sawtooth 0 6 0.677012 0.784
		tcMod rotate 36
		tcMod stretch sawtooth 1 -0.7 0.677012 0.784
	}
}

textures/terminus/zzmon_fire_13
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_14
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 51 sawtooth 0 1 0.719682 0.784
	deformvertexes move -2.10451 -0.533267 0 inversesawtooth 0 1 0.719682 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.71968 0.784
		alphagen wave sawtooth 0 6 0.719682 0.784
		tcMod rotate 82
		tcMod stretch sawtooth 1 -0.7 0.719682 0.784
	}
}

textures/terminus/zzmon_fire_14
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_15
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 29 sawtooth 0 1 0.761582 0.784
	deformvertexes move -6.53379 -4.58198 0 inversesawtooth -0.125309 1 0.761582 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.76158 0.784
		alphagen wave sawtooth 0 6 0.761582 0.784
		tcMod rotate -4
		tcMod stretch sawtooth 1 -0.7 0.761582 0.784
	}
}

textures/terminus/zzmon_fire_15
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_16
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 29 sawtooth 0 1 0.80278 0.784
	deformvertexes move 7.94022 0.798698 0 inversesawtooth 0 1 0.80278 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.80278 0.784
		alphagen wave sawtooth 0 6 0.80278 0.784
		tcMod rotate 60
		tcMod stretch sawtooth 1 -0.7 0.80278 0.784
	}
}

textures/terminus/zzmon_fire_16
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_17
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 21 sawtooth 0 1 0.843334 0.784
	deformvertexes move -4.8337 8.16552 0 inversesawtooth 0 1 0.843334 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.84333 0.784
		alphagen wave sawtooth 0 6 0.843334 0.784
		tcMod rotate 4
		tcMod stretch sawtooth 1 -0.7 0.843334 0.784
	}
}

textures/terminus/zzmon_fire_17
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_18
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 39 sawtooth 0 1 0.883292 0.784
	deformvertexes move -5.90123 -5.35486 0 inversesawtooth 0 1 0.883292 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.88329 0.784
		alphagen wave sawtooth 0 6 0.883292 0.784
		tcMod rotate 12
		tcMod stretch sawtooth 1 -0.7 0.883292 0.784
	}
}

textures/terminus/zzmon_fire_18
{
	qer_editorimage textures/terminus/fire
	q3map_cloneshader textures/terminus/zzmon_fire_19
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 35 sawtooth 0 1 0.922698 0.784
	deformvertexes move 3.42269 -0.317997 0 inversesawtooth 0 1 0.922698 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.9227 0.784
		alphagen wave sawtooth 0 6 0.922698 0.784
		tcMod rotate 47
		tcMod stretch sawtooth 1 -0.7 0.922698 0.784
	}
}

textures/terminus/zzmon_fire_19
{
	qer_editorimage textures/terminus/fire
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 49 sawtooth 0 1 0.96159 0.784
	deformvertexes move 1.18481 1.6218 0 inversesawtooth -0.497887 1 0.96159 0.784
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/fire
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave sawtooth 1 -1 1.96159 0.784
		alphagen wave sawtooth 0 6 0.96159 0.784
		tcMod rotate 7
		tcMod stretch sawtooth 1 -0.7 0.96159 0.784
	}
}

// Generated by Frozen Sand Particle Studio
// Mon Sep 26 21:02:12 2011


textures/terminus/mon_smoke
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 126 sawtooth 0.0396825 1 0 0.172
	deformvertexes move 22.6205 64.698 0 sawtooth 0 1 0 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0 0.172
		alphagen wave sawtooth 1.2 -1.2 0 0.172
		tcMod rotate -4
		tcMod stretch sawtooth 0.4 0.6 0 0.172
	}
}

textures/terminus/zzmon_smoke_1
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 117 sawtooth -0.00854701 1 0.05 0.172
	deformvertexes move 1.48696 61.9822 0 sawtooth -0.0806452 1 0.05 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.05 0.172
		alphagen wave sawtooth 1.2 -1.2 0.05 0.172
		tcMod rotate 2
		tcMod stretch sawtooth 0.4 0.6 0.05 0.172
	}
}

textures/terminus/zzmon_smoke_2
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 141 sawtooth 0 1 0.1 0.172
	deformvertexes move -12.5425 45.7477 0 sawtooth -0.0421622 1 0.1 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.1 0.172
		alphagen wave sawtooth 1.2 -1.2 0.1 0.172
		tcMod rotate -1
		tcMod stretch sawtooth 0.4 0.6 0.1 0.172
	}
}

textures/terminus/zzmon_smoke_3
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 146 sawtooth 0.0205479 1 0.15 0.172
	deformvertexes move 6.80269 58.0042 0 sawtooth 0.0342456 1 0.15 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.15 0.172
		alphagen wave sawtooth 1.2 -1.2 0.15 0.172
		tcMod rotate -1
		tcMod stretch sawtooth 0.4 0.6 0.15 0.172
	}
}

textures/terminus/zzmon_smoke_4
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 153 sawtooth -0.0196078 1 0.2 0.172
	deformvertexes move 9.35396 55.3693 0 sawtooth -0.0356164 1 0.2 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.2 0.172
		alphagen wave sawtooth 1.2 -1.2 0.2 0.172
		tcMod rotate -1
		tcMod stretch sawtooth 0.4 0.6 0.2 0.172
	}
}

textures/terminus/zzmon_smoke_5
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 96 sawtooth -0.0625 1 0.25 0.172
	deformvertexes move 2.16436 33.6741 0 sawtooth -0.0889058 1 0.25 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.25 0.172
		alphagen wave sawtooth 1.2 -1.2 0.25 0.172
		tcMod rotate -7
		tcMod stretch sawtooth 0.4 0.6 0.25 0.172
	}
}

textures/terminus/zzmon_smoke_6
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_7
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 101 sawtooth -0.039604 1 0.3 0.172
	deformvertexes move 1.46586 26.6691 0 sawtooth -0.03744 1 0.3 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.3 0.172
		alphagen wave sawtooth 1.2 -1.2 0.3 0.172
		tcMod rotate -12
		tcMod stretch sawtooth 0.4 0.6 0.3 0.172
	}
}

textures/terminus/zzmon_smoke_7
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_8
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 78 sawtooth 0.0641026 1 0.35 0.172
	deformvertexes move 1.24131 32.6431 0 sawtooth 0.0612245 1 0.35 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.35 0.172
		alphagen wave sawtooth 1.2 -1.2 0.35 0.172
		tcMod rotate 1
		tcMod stretch sawtooth 0.4 0.6 0.35 0.172
	}
}

textures/terminus/zzmon_smoke_8
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_9
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 114 sawtooth 0.0263158 1 0.4 0.172
	deformvertexes move 11.357 27.5732 0 sawtooth 0.100602 1 0.4 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.4 0.172
		alphagen wave sawtooth 1.2 -1.2 0.4 0.172
		tcMod rotate 13
		tcMod stretch sawtooth 0.4 0.6 0.4 0.172
	}
}

textures/terminus/zzmon_smoke_9
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_10
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 112 sawtooth -0.0535714 1 0.45 0.172
	deformvertexes move 3.31969 45.9143 0 sawtooth 0 1 0.45 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.45 0.172
		alphagen wave sawtooth 1.2 -1.2 0.45 0.172
		tcMod rotate -6
		tcMod stretch sawtooth 0.4 0.6 0.45 0.172
	}
}

textures/terminus/zzmon_smoke_10
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_11
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 107 sawtooth 0.0186916 1 0.5 0.172
	deformvertexes move 3.66688 65.9665 0 sawtooth 0.0151358 1 0.5 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.5 0.172
		alphagen wave sawtooth 1.2 -1.2 0.5 0.172
		tcMod rotate 10
		tcMod stretch sawtooth 0.4 0.6 0.5 0.172
	}
}

textures/terminus/zzmon_smoke_11
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_12
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 116 sawtooth -0.0172414 1 0.55 0.172
	deformvertexes move 1.29595 38.5851 0 sawtooth 0.0259021 1 0.55 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.55 0.172
		alphagen wave sawtooth 1.2 -1.2 0.55 0.172
		tcMod rotate -8
		tcMod stretch sawtooth 0.4 0.6 0.55 0.172
	}
}

textures/terminus/zzmon_smoke_12
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_13
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 86 sawtooth -0.0697674 1 0.6 0.172
	deformvertexes move 23.9357 51.5236 0 sawtooth 0.0704077 1 0.6 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.6 0.172
		alphagen wave sawtooth 1.2 -1.2 0.6 0.172
		tcMod rotate -7
		tcMod stretch sawtooth 0.4 0.6 0.6 0.172
	}
}

textures/terminus/zzmon_smoke_13
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_14
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 84 sawtooth 0.0119048 1 0.65 0.172
	deformvertexes move 5.5878 17.1377 0 sawtooth 0 1 0.65 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.65 0.172
		alphagen wave sawtooth 1.2 -1.2 0.65 0.172
		tcMod rotate 11
		tcMod stretch sawtooth 0.4 0.6 0.65 0.172
	}
}

textures/terminus/zzmon_smoke_14
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_15
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 103 sawtooth -0.0679612 1 0.7 0.172
	deformvertexes move 3.97353 23.1573 0 sawtooth 0 1 0.7 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.7 0.172
		alphagen wave sawtooth 1.2 -1.2 0.7 0.172
		tcMod rotate 13
		tcMod stretch sawtooth 0.4 0.6 0.7 0.172
	}
}

textures/terminus/zzmon_smoke_15
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_16
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 125 sawtooth -0.008 1 0.75 0.172
	deformvertexes move -7.25406 33.3658 0 sawtooth 0.0585732 1 0.75 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.75 0.172
		alphagen wave sawtooth 1.2 -1.2 0.75 0.172
		tcMod rotate -5
		tcMod stretch sawtooth 0.4 0.6 0.75 0.172
	}
}

textures/terminus/zzmon_smoke_16
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_17
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 120 sawtooth -0.05 1 0.8 0.172
	deformvertexes move 7.94535 50.559 0 sawtooth -0.0976954 1 0.8 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.8 0.172
		alphagen wave sawtooth 1.2 -1.2 0.8 0.172
		tcMod rotate 1
		tcMod stretch sawtooth 0.4 0.6 0.8 0.172
	}
}

textures/terminus/zzmon_smoke_17
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_18
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 96 sawtooth 0.0416667 1 0.85 0.172
	deformvertexes move -11.6436 39.0444 0 sawtooth 0.0490875 1 0.85 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.85 0.172
		alphagen wave sawtooth 1.2 -1.2 0.85 0.172
		tcMod rotate 6
		tcMod stretch sawtooth 0.4 0.6 0.85 0.172
	}
}

textures/terminus/zzmon_smoke_18
{
	qer_editorimage textures/terminus/smoke
	q3map_cloneshader textures/terminus/zzmon_smoke_19
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 87 sawtooth -0.0574713 1 0.9 0.172
	deformvertexes move 12.5756 33.9509 0 sawtooth -0.110482 1 0.9 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.9 0.172
		alphagen wave sawtooth 1.2 -1.2 0.9 0.172
		tcMod rotate -4
		tcMod stretch sawtooth 0.4 0.6 0.9 0.172
	}
}

textures/terminus/zzmon_smoke_19
{
	qer_editorimage textures/terminus/smoke
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 152 sawtooth 0 1 0.95 0.172
	deformvertexes move 8.68354 44.9292 0 sawtooth -0.0218528 1 0.95 0.172
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/smoke
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen wave sawtooth 0 0.5 0.95 0.172
		alphagen wave sawtooth 1.2 -1.2 0.95 0.172
		tcMod rotate -2
		tcMod stretch sawtooth 0.4 0.6 0.95 0.172
	}
}

// Generated by Frozen Sand Particle Studio
// Tue Dec 27 14:58:59 2011


textures/terminus/steam
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1 1.2181
	deformvertexes move -46.878 -20.0861 0 sawtooth 0.137255 1 1.1733 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1 1.2181
		alphagen const 5
		tcMod rotate 60
		tcMod stretch inversesawtooth 1 0 1.56 1.2181
	}
}

textures/terminus/zzsteam_1
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.05113 1.2181
	deformvertexes move 46.4687 -21.0156 0 sawtooth -0.0196078 1 1.22443 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.05113 1.2181
		alphagen const 5
		tcMod rotate 188
		tcMod stretch inversesawtooth 1 0 1.61113 1.2181
	}
}

textures/terminus/zzsteam_2
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.0913 1.2181
	deformvertexes move -31.2069 -40.3377 0 sawtooth -0.0196078 1 1.2646 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.0913 1.2181
		alphagen const 5
		tcMod rotate 11
		tcMod stretch inversesawtooth 1 0 1.6513 1.2181
	}
}

textures/terminus/zzsteam_3
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.12815 1.2181
	deformvertexes move -5.83615 50.665 0 sawtooth -0.352941 1 1.30145 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.12815 1.2181
		alphagen const 5
		tcMod rotate -2
		tcMod stretch inversesawtooth 1 0 1.68815 1.2181
	}
}

textures/terminus/zzsteam_4
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.163 1.2181
	deformvertexes move -50.9591 2.04227 0 sawtooth -0.0196078 1 1.3363 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.163 1.2181
		alphagen const 5
		tcMod rotate 192
		tcMod stretch inversesawtooth 1 0 1.723 1.2181
	}
}

textures/terminus/zzsteam_5
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.19645 1.2181
	deformvertexes move 39.561 32.1859 0 sawtooth -0.117647 1 1.36975 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.19645 1.2181
		alphagen const 5
		tcMod rotate 56
		tcMod stretch inversesawtooth 1 0 1.75645 1.2181
	}
}

textures/terminus/zzsteam_6
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_7
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.2288 1.2181
	deformvertexes move 42.0486 28.8603 0 sawtooth -0.0392157 1 1.4021 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.2288 1.2181
		alphagen const 5
		tcMod rotate 152
		tcMod stretch inversesawtooth 1 0 1.7888 1.2181
	}
}

textures/terminus/zzsteam_7
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_8
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.26029 1.2181
	deformvertexes move 25.8714 -43.9508 0 sawtooth 0.27451 1 1.43359 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.26029 1.2181
		alphagen const 5
		tcMod rotate 206
		tcMod stretch inversesawtooth 1 0 1.82029 1.2181
	}
}

textures/terminus/zzsteam_8
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_9
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.29104 1.2181
	deformvertexes move -13.6686 49.1342 0 sawtooth -0.0980392 1 1.46434 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.29104 1.2181
		alphagen const 5
		tcMod rotate 172
		tcMod stretch inversesawtooth 1 0 1.85104 1.2181
	}
}

textures/terminus/zzsteam_9
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_10
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.32117 1.2181
	deformvertexes move -21.7462 46.1314 0 sawtooth -0.352941 1 1.49447 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.32117 1.2181
		alphagen const 5
		tcMod rotate -56
		tcMod stretch inversesawtooth 1 0 1.88117 1.2181
	}
}

textures/terminus/zzsteam_10
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_11
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.35075 1.2181
	deformvertexes move 20.7606 -46.5832 0 sawtooth -0.235294 1 1.52405 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.35075 1.2181
		alphagen const 5
		tcMod rotate -24
		tcMod stretch inversesawtooth 1 0 1.91075 1.2181
	}
}

textures/terminus/zzsteam_11
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_12
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.37985 1.2181
	deformvertexes move -27.8214 -42.7431 0 sawtooth 0.117647 1 1.55315 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.37985 1.2181
		alphagen const 5
		tcMod rotate 61
		tcMod stretch inversesawtooth 1 0 1.93985 1.2181
	}
}

textures/terminus/zzsteam_12
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_13
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.40852 1.2181
	deformvertexes move -5.51859 50.7005 0 sawtooth -0.235294 1 1.58182 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.40852 1.2181
		alphagen const 5
		tcMod rotate 208
		tcMod stretch inversesawtooth 1 0 1.96852 1.2181
	}
}

textures/terminus/zzsteam_13
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_14
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.4368 1.2181
	deformvertexes move 50.5162 7.00791 0 sawtooth 0.117647 1 1.6101 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.4368 1.2181
		alphagen const 5
		tcMod rotate 77
		tcMod stretch inversesawtooth 1 0 1.9968 1.2181
	}
}

textures/terminus/zzsteam_14
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_15
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.46473 1.2181
	deformvertexes move -42.4765 -28.2267 0 sawtooth 0.137255 1 1.63803 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.46473 1.2181
		alphagen const 5
		tcMod rotate 36
		tcMod stretch inversesawtooth 1 0 2.02473 1.2181
	}
}

textures/terminus/zzsteam_15
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_16
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.49234 1.2181
	deformvertexes move 21.5705 46.2138 0 sawtooth -0.215686 1 1.66564 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.49234 1.2181
		alphagen const 5
		tcMod rotate -79
		tcMod stretch inversesawtooth 1 0 2.05234 1.2181
	}
}

textures/terminus/zzsteam_16
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_17
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.51964 1.2181
	deformvertexes move 50.8099 -4.39972 0 sawtooth 0.117647 1 1.69294 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.51964 1.2181
		alphagen const 5
		tcMod rotate 204
		tcMod stretch inversesawtooth 1 0 2.07964 1.2181
	}
}

textures/terminus/zzsteam_17
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_18
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.54666 1.2181
	deformvertexes move -7.42029 50.4573 0 sawtooth 0.0392157 1 1.71996 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.54666 1.2181
		alphagen const 5
		tcMod rotate 72
		tcMod stretch inversesawtooth 1 0 2.10666 1.2181
	}
}

textures/terminus/zzsteam_18
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_19
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.57343 1.2181
	deformvertexes move 49.6513 -11.6511 0 sawtooth 0.313726 1 1.74673 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.57343 1.2181
		alphagen const 5
		tcMod rotate -74
		tcMod stretch inversesawtooth 1 0 2.13343 1.2181
	}
}

textures/terminus/zzsteam_19
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_20
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.59995 1.2181
	deformvertexes move 48.4182 16.0212 0 sawtooth -0.0980392 1 1.77325 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.59995 1.2181
		alphagen const 5
		tcMod rotate 145
		tcMod stretch inversesawtooth 1 0 2.15995 1.2181
	}
}

textures/terminus/zzsteam_20
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_21
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.62625 1.2181
	deformvertexes move -25.9205 -43.9218 0 sawtooth 0.137255 1 1.79955 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.62625 1.2181
		alphagen const 5
		tcMod rotate -94
		tcMod stretch inversesawtooth 1 0 2.18625 1.2181
	}
}

textures/terminus/zzsteam_21
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_22
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.65233 1.2181
	deformvertexes move 5.00773 50.7535 0 sawtooth -0.0196078 1 1.82563 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.65233 1.2181
		alphagen const 5
		tcMod rotate 134
		tcMod stretch inversesawtooth 1 0 2.21233 1.2181
	}
}

textures/terminus/zzsteam_22
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_23
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.67821 1.2181
	deformvertexes move 1.88841 -50.965 0 sawtooth -0.117647 1 1.85151 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.67821 1.2181
		alphagen const 5
		tcMod rotate -5
		tcMod stretch inversesawtooth 1 0 2.23821 1.2181
	}
}

textures/terminus/zzsteam_23
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_24
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.7039 1.2181
	deformvertexes move 27.7161 42.8114 0 sawtooth -0.254902 1 1.8772 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.7039 1.2181
		alphagen const 5
		tcMod rotate 121
		tcMod stretch inversesawtooth 1 0 2.2639 1.2181
	}
}

textures/terminus/zzsteam_24
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_25
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.7294 1.2181
	deformvertexes move -39.8403 -31.8394 0 sawtooth 0.235294 1 1.9027 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.7294 1.2181
		alphagen const 5
		tcMod rotate -8
		tcMod stretch inversesawtooth 1 0 2.2894 1.2181
	}
}

textures/terminus/zzsteam_25
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_26
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.75473 1.2181
	deformvertexes move 29.8819 -41.3288 0 sawtooth 0.372549 1 1.92803 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.75473 1.2181
		alphagen const 5
		tcMod rotate 45
		tcMod stretch inversesawtooth 1 0 2.31473 1.2181
	}
}

textures/terminus/zzsteam_26
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_27
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.7799 1.2181
	deformvertexes move -5.51859 50.7005 0 sawtooth 0.0980392 1 1.9532 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.7799 1.2181
		alphagen const 5
		tcMod rotate -82
		tcMod stretch inversesawtooth 1 0 2.3399 1.2181
	}
}

textures/terminus/zzsteam_27
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_28
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.80491 1.2181
	deformvertexes move 29.6224 -41.5152 0 sawtooth 0 1 1.97821 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.80491 1.2181
		alphagen const 5
		tcMod rotate 86
		tcMod stretch inversesawtooth 1 0 2.36491 1.2181
	}
}

textures/terminus/zzsteam_28
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_29
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.82976 1.2181
	deformvertexes move -31.7636 39.9008 0 sawtooth 0.0784314 1 2.00306 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.82976 1.2181
		alphagen const 5
		tcMod rotate 95
		tcMod stretch inversesawtooth 1 0 2.38976 1.2181
	}
}

textures/terminus/zzsteam_29
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_30
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.85447 1.2181
	deformvertexes move 41.8669 29.1232 0 sawtooth 0.0980392 1 2.02777 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.85447 1.2181
		alphagen const 5
		tcMod rotate -29
		tcMod stretch inversesawtooth 1 0 2.41447 1.2181
	}
}

textures/terminus/zzsteam_30
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_31
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.87905 1.2181
	deformvertexes move -34.4361 37.6186 0 sawtooth -0.0980392 1 2.05235 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.87905 1.2181
		alphagen const 5
		tcMod rotate 182
		tcMod stretch inversesawtooth 1 0 2.43905 1.2181
	}
}

textures/terminus/zzsteam_31
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_32
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.90349 1.2181
	deformvertexes move 47.1999 19.3177 0 sawtooth 0.235294 1 2.07679 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.90349 1.2181
		alphagen const 5
		tcMod rotate 121
		tcMod stretch inversesawtooth 1 0 2.46349 1.2181
	}
}

textures/terminus/zzsteam_32
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_33
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.9278 1.2181
	deformvertexes move -32.013 39.701 0 sawtooth -0.117647 1 2.1011 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.9278 1.2181
		alphagen const 5
		tcMod rotate 204
		tcMod stretch inversesawtooth 1 0 2.4878 1.2181
	}
}

textures/terminus/zzsteam_33
{
	qer_editorimage textures/terminus/steam
	q3map_cloneshader textures/terminus/zzsteam_34
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.95198 1.2181
	deformvertexes move 3.0966 50.9059 0 sawtooth -0.0980392 1 2.12528 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.95198 1.2181
		alphagen const 5
		tcMod rotate 155
		tcMod stretch inversesawtooth 1 0 2.51198 1.2181
	}
}

textures/terminus/zzsteam_34
{
	qer_editorimage textures/terminus/steam
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 160 inversesawtooth 0 1 1.97605 1.2181
	deformvertexes move -43.5431 26.5517 0 sawtooth 0.372549 1 2.14935 1.2181
	deformvertexes autosprite
	cull disable
	{
		clampmap textures/terminus/steam
		blendfunc GL_SRC_ALPHA GL_ONE
		rgbgen wave inversesawtooth -0.8667 5.8667 1.97605 1.2181
		alphagen const 5
		tcMod rotate 7
		tcMod stretch inversesawtooth 1 0 2.53605 1.2181
	}
}
